// Device Database for IKU Gadget
// Comprehensive list of mobile devices organized by OS and Brand

export type OsKey = "iOS" | "Android";

export const DEVICE_DATA: Record<OsKey, Record<string, string[]>> = {
  iOS: {
    Apple: [
      // iPhone 4 series
      "iPhone 4",
      "iPhone 4S",
      // iPhone 5 series
      "iPhone 5",
      "iPhone 5C",
      "iPhone 5S",
      // iPhone 6 series
      "iPhone 6",
      "iPhone 6 Plus",
      "iPhone 6S",
      "iPhone 6S Plus",
      // iPhone SE series
      "iPhone SE (1st Gen)",
      "iPhone SE (2nd Gen)",
      "iPhone SE (3rd Gen)",
      // iPhone 7 series
      "iPhone 7",
      "iPhone 7 Plus",
      // iPhone 8 series
      "iPhone 8",
      "iPhone 8 Plus",
      // iPhone X series
      "iPhone X",
      "iPhone XR",
      "iPhone XS",
      "iPhone XS Max",
      // iPhone 11 series
      "iPhone 11",
      "iPhone 11 Pro",
      "iPhone 11 Pro Max",
      // iPhone 12 series
      "iPhone 12",
      "iPhone 12 Mini",
      "iPhone 12 Pro",
      "iPhone 12 Pro Max",
      // iPhone 13 series
      "iPhone 13",
      "iPhone 13 Mini",
      "iPhone 13 Pro",
      "iPhone 13 Pro Max",
      // iPhone 14 series
      "iPhone 14",
      "iPhone 14 Plus",
      "iPhone 14 Pro",
      "iPhone 14 Pro Max",
      // iPhone 15 series
      "iPhone 15",
      "iPhone 15 Plus",
      "iPhone 15 Pro",
      "iPhone 15 Pro Max",
      // iPhone 16 series
      "iPhone 16",
      "iPhone 16 Plus",
      "iPhone 16 Pro",
      "iPhone 16 Pro Max",
      // iPad (standard)
      "iPad (1st Gen)",
      "iPad (2nd Gen)",
      "iPad (3rd Gen)",
      "iPad (4th Gen)",
      "iPad (5th Gen)",
      "iPad (6th Gen)",
      "iPad (7th Gen)",
      "iPad (8th Gen)",
      "iPad (9th Gen)",
      "iPad (10th Gen)",
      // iPad Air
      "iPad Air (1st Gen)",
      "iPad Air 2",
      "iPad Air (3rd Gen)",
      "iPad Air (4th Gen)",
      "iPad Air (5th Gen)",
      "iPad Air 11-inch (M2)",
      "iPad Air 13-inch (M2)",
      // iPad Pro
      "iPad Pro 9.7-inch",
      "iPad Pro 10.5-inch",
      "iPad Pro 12.9-inch (1st Gen)",
      "iPad Pro 12.9-inch (2nd Gen)",
      "iPad Pro 11-inch (1st Gen)",
      "iPad Pro 11-inch (2nd Gen)",
      "iPad Pro 11-inch (3rd Gen)",
      "iPad Pro 11-inch (4th Gen)",
      "iPad Pro 11-inch (M4)",
      "iPad Pro 12.9-inch (3rd Gen)",
      "iPad Pro 12.9-inch (4th Gen)",
      "iPad Pro 12.9-inch (5th Gen)",
      "iPad Pro 12.9-inch (6th Gen)",
      "iPad Pro 13-inch (M4)",
      // iPad Mini
      "iPad Mini (1st Gen)",
      "iPad Mini 2",
      "iPad Mini 3",
      "iPad Mini 4",
      "iPad Mini (5th Gen)",
      "iPad Mini (6th Gen)",
    ],
  },
  Android: {
    Samsung: [
      // Galaxy S series
      "Galaxy S",
      "Galaxy S II",
      "Galaxy S III",
      "Galaxy S4",
      "Galaxy S5",
      "Galaxy S6",
      "Galaxy S6 Edge",
      "Galaxy S6 Edge+",
      "Galaxy S7",
      "Galaxy S7 Edge",
      "Galaxy S8",
      "Galaxy S8+",
      "Galaxy S9",
      "Galaxy S9+",
      "Galaxy S10e",
      "Galaxy S10",
      "Galaxy S10+",
      "Galaxy S10 5G",
      "Galaxy S20",
      "Galaxy S20+",
      "Galaxy S20 Ultra",
      "Galaxy S20 FE",
      "Galaxy S21",
      "Galaxy S21+",
      "Galaxy S21 Ultra",
      "Galaxy S21 FE",
      "Galaxy S22",
      "Galaxy S22+",
      "Galaxy S22 Ultra",
      "Galaxy S23",
      "Galaxy S23+",
      "Galaxy S23 Ultra",
      "Galaxy S23 FE",
      "Galaxy S24",
      "Galaxy S24+",
      "Galaxy S24 Ultra",
      "Galaxy S24 FE",
      // Galaxy Note series
      "Galaxy Note",
      "Galaxy Note II",
      "Galaxy Note 3",
      "Galaxy Note 4",
      "Galaxy Note 5",
      "Galaxy Note 7",
      "Galaxy Note 8",
      "Galaxy Note 9",
      "Galaxy Note 10",
      "Galaxy Note 10+",
      "Galaxy Note 10 Lite",
      "Galaxy Note 20",
      "Galaxy Note 20 Ultra",
      // Galaxy A series
      "Galaxy A01",
      "Galaxy A02",
      "Galaxy A02s",
      "Galaxy A03",
      "Galaxy A03s",
      "Galaxy A03 Core",
      "Galaxy A04",
      "Galaxy A04s",
      "Galaxy A04e",
      "Galaxy A05",
      "Galaxy A05s",
      "Galaxy A06",
      "Galaxy A10",
      "Galaxy A10s",
      "Galaxy A10e",
      "Galaxy A11",
      "Galaxy A12",
      "Galaxy A13",
      "Galaxy A13 5G",
      "Galaxy A14",
      "Galaxy A14 5G",
      "Galaxy A15",
      "Galaxy A15 5G",
      "Galaxy A20",
      "Galaxy A20s",
      "Galaxy A20e",
      "Galaxy A21",
      "Galaxy A21s",
      "Galaxy A22",
      "Galaxy A22 5G",
      "Galaxy A23",
      "Galaxy A23 5G",
      "Galaxy A24",
      "Galaxy A25 5G",
      "Galaxy A30",
      "Galaxy A30s",
      "Galaxy A31",
      "Galaxy A32",
      "Galaxy A32 5G",
      "Galaxy A33 5G",
      "Galaxy A34 5G",
      "Galaxy A35 5G",
      "Galaxy A40",
      "Galaxy A41",
      "Galaxy A42 5G",
      "Galaxy A50",
      "Galaxy A50s",
      "Galaxy A51",
      "Galaxy A51 5G",
      "Galaxy A52",
      "Galaxy A52s 5G",
      "Galaxy A53 5G",
      "Galaxy A54 5G",
      "Galaxy A55 5G",
      "Galaxy A70",
      "Galaxy A70s",
      "Galaxy A71",
      "Galaxy A71 5G",
      "Galaxy A72",
      "Galaxy A73 5G",
      "Galaxy A80",
      "Galaxy A90 5G",
      // Galaxy M series
      "Galaxy M01",
      "Galaxy M01s",
      "Galaxy M01 Core",
      "Galaxy M02",
      "Galaxy M02s",
      "Galaxy M03",
      "Galaxy M03s",
      "Galaxy M04",
      "Galaxy M10",
      "Galaxy M10s",
      "Galaxy M11",
      "Galaxy M12",
      "Galaxy M13",
      "Galaxy M13 5G",
      "Galaxy M14 5G",
      "Galaxy M20",
      "Galaxy M21",
      "Galaxy M21s",
      "Galaxy M22",
      "Galaxy M23 5G",
      "Galaxy M24",
      "Galaxy M30",
      "Galaxy M30s",
      "Galaxy M31",
      "Galaxy M31s",
      "Galaxy M32",
      "Galaxy M32 5G",
      "Galaxy M33 5G",
      "Galaxy M34 5G",
      "Galaxy M40",
      "Galaxy M42 5G",
      "Galaxy M51",
      "Galaxy M52 5G",
      "Galaxy M53 5G",
      "Galaxy M54 5G",
      // Galaxy Z series
      "Galaxy Z Fold",
      "Galaxy Z Fold 2",
      "Galaxy Z Fold 3",
      "Galaxy Z Fold 4",
      "Galaxy Z Fold 5",
      "Galaxy Z Flip",
      "Galaxy Z Flip 3",
      "Galaxy Z Flip 4",
      "Galaxy Z Flip 5",
      // Galaxy F series
      "Galaxy F04",
      "Galaxy F12",
      "Galaxy F13",
      "Galaxy F14 5G",
      "Galaxy F22",
      "Galaxy F23 5G",
      "Galaxy F34 5G",
      "Galaxy F41",
      "Galaxy F42 5G",
      "Galaxy F54 5G",
      // Galaxy Tab S series
      "Galaxy Tab S6",
      "Galaxy Tab S6 Lite",
      "Galaxy Tab S7",
      "Galaxy Tab S7+",
      "Galaxy Tab S7 FE",
      "Galaxy Tab S8",
      "Galaxy Tab S8+",
      "Galaxy Tab S8 Ultra",
      "Galaxy Tab S9",
      "Galaxy Tab S9+",
      "Galaxy Tab S9 Ultra",
      "Galaxy Tab S9 FE",
    ],

    Xiaomi: [
      // Mi series
      "Mi 1",
      "Mi 2",
      "Mi 2S",
      "Mi 3",
      "Mi 4",
      "Mi 4i",
      "Mi 4c",
      "Mi 5",
      "Mi 5s",
      "Mi 5s Plus",
      "Mi 5X",
      "Mi 6",
      "Mi 6X",
      "Mi 8",
      "Mi 8 SE",
      "Mi 8 Lite",
      "Mi 8 Pro",
      "Mi 9",
      "Mi 9 SE",
      "Mi 9T",
      "Mi 9T Pro",
      "Mi 9 Lite",
      "Mi 10",
      "Mi 10 Pro",
      "Mi 10 Lite",
      "Mi 10T",
      "Mi 10T Pro",
      "Mi 10T Lite",
      "Mi 10i",
      "Mi 11",
      "Mi 11 Lite",
      "Mi 11 Lite 5G",
      "Mi 11 Lite NE",
      "Mi 11 Ultra",
      "Mi 11X",
      "Mi 11X Pro",
      "Mi 11i",
      // Xiaomi numbered series
      "Xiaomi 12",
      "Xiaomi 12 Pro",
      "Xiaomi 12 Lite",
      "Xiaomi 12X",
      "Xiaomi 12S",
      "Xiaomi 12S Pro",
      "Xiaomi 12S Ultra",
      "Xiaomi 12T",
      "Xiaomi 12T Pro",
      "Xiaomi 13",
      "Xiaomi 13 Pro",
      "Xiaomi 13 Lite",
      "Xiaomi 13 Ultra",
      "Xiaomi 13T",
      "Xiaomi 13T Pro",
      "Xiaomi 14",
      "Xiaomi 14 Pro",
      "Xiaomi 14 Ultra",
      "Xiaomi 14T",
      "Xiaomi 14T Pro",
      // POCO series
      "POCO F1",
      "POCO F2 Pro",
      "POCO F3",
      "POCO F3 GT",
      "POCO F4",
      "POCO F4 GT",
      "POCO F5",
      "POCO F5 Pro",
      "POCO F6",
      "POCO F6 Pro",
      "POCO X2",
      "POCO X3",
      "POCO X3 NFC",
      "POCO X3 Pro",
      "POCO X3 GT",
      "POCO X4 Pro 5G",
      "POCO X4 GT",
      "POCO X5",
      "POCO X5 Pro",
      "POCO X6",
      "POCO X6 Pro",
      "POCO M2",
      "POCO M2 Pro",
      "POCO M2 Reloaded",
      "POCO M3",
      "POCO M3 Pro",
      "POCO M4 Pro",
      "POCO M4 Pro 5G",
      "POCO M4 5G",
      "POCO M5",
      "POCO M5s",
      "POCO M6 Pro",
      "POCO M6 Pro 5G",
      "POCO C3",
      "POCO C31",
      "POCO C40",
      "POCO C50",
      "POCO C51",
      "POCO C55",
      "POCO C65",
      // Xiaomi Pad series
      "Xiaomi Pad 5",
      "Xiaomi Pad 5 Pro",
      "Xiaomi Pad 6",
      "Xiaomi Pad 6 Pro",
    ],

    Redmi: [
      // Redmi Note series
      "Redmi Note",
      "Redmi Note 2",
      "Redmi Note 3",
      "Redmi Note 4",
      "Redmi Note 4X",
      "Redmi Note 5",
      "Redmi Note 5 Pro",
      "Redmi Note 5A",
      "Redmi Note 6 Pro",
      "Redmi Note 7",
      "Redmi Note 7 Pro",
      "Redmi Note 7S",
      "Redmi Note 8",
      "Redmi Note 8 Pro",
      "Redmi Note 8T",
      "Redmi Note 8 2021",
      "Redmi Note 9",
      "Redmi Note 9 Pro",
      "Redmi Note 9 Pro Max",
      "Redmi Note 9S",
      "Redmi Note 9T",
      "Redmi Note 10",
      "Redmi Note 10 Pro",
      "Redmi Note 10 Pro Max",
      "Redmi Note 10S",
      "Redmi Note 10T",
      "Redmi Note 10 5G",
      "Redmi Note 11",
      "Redmi Note 11 Pro",
      "Redmi Note 11 Pro+",
      "Redmi Note 11S",
      "Redmi Note 11T",
      "Redmi Note 11 5G",
      "Redmi Note 11 SE",
      "Redmi Note 12",
      "Redmi Note 12 Pro",
      "Redmi Note 12 Pro+",
      "Redmi Note 12S",
      "Redmi Note 12 5G",
      "Redmi Note 12 Turbo",
      "Redmi Note 13",
      "Redmi Note 13 Pro",
      "Redmi Note 13 Pro+",
      "Redmi Note 13 5G",
      // Redmi numbered series
      "Redmi 1",
      "Redmi 1S",
      "Redmi 2",
      "Redmi 2 Prime",
      "Redmi 3",
      "Redmi 3S",
      "Redmi 3X",
      "Redmi 4",
      "Redmi 4A",
      "Redmi 4X",
      "Redmi 5",
      "Redmi 5A",
      "Redmi 5 Plus",
      "Redmi 6",
      "Redmi 6A",
      "Redmi 6 Pro",
      "Redmi 7",
      "Redmi 7A",
      "Redmi 8",
      "Redmi 8A",
      "Redmi 8A Pro",
      "Redmi 8A Dual",
      "Redmi 9",
      "Redmi 9A",
      "Redmi 9C",
      "Redmi 9i",
      "Redmi 9T",
      "Redmi 9 Prime",
      "Redmi 9 Power",
      "Redmi 10",
      "Redmi 10A",
      "Redmi 10C",
      "Redmi 10 Prime",
      "Redmi 10 2022",
      "Redmi 10 5G",
      "Redmi 11 Prime",
      "Redmi 11 Prime 5G",
      "Redmi 12",
      "Redmi 12C",
      "Redmi 12 5G",
      "Redmi 13",
      "Redmi 13C",
      "Redmi 13C 5G",
      // Redmi K series
      "Redmi K20",
      "Redmi K20 Pro",
      "Redmi K30",
      "Redmi K30 Pro",
      "Redmi K30 5G",
      "Redmi K30i 5G",
      "Redmi K30S Ultra",
      "Redmi K40",
      "Redmi K40 Pro",
      "Redmi K40 Pro+",
      "Redmi K40 Gaming",
      "Redmi K50",
      "Redmi K50 Pro",
      "Redmi K50 Gaming",
      "Redmi K50i",
      "Redmi K60",
      "Redmi K60 Pro",
      "Redmi K60 Ultra",
      "Redmi K70",
      "Redmi K70 Pro",
      // Redmi A series
      "Redmi A1",
      "Redmi A1+",
      "Redmi A2",
      "Redmi A2+",
      "Redmi A3",
    ],

    OPPO: [
      // Find X series
      "Find X",
      "Find X2",
      "Find X2 Pro",
      "Find X2 Neo",
      "Find X2 Lite",
      "Find X3",
      "Find X3 Pro",
      "Find X3 Neo",
      "Find X3 Lite",
      "Find X5",
      "Find X5 Pro",
      "Find X5 Lite",
      "Find X6",
      "Find X6 Pro",
      "Find X7",
      "Find X7 Ultra",
      // Reno series
      "Reno",
      "Reno 2",
      "Reno 2F",
      "Reno 2Z",
      "Reno 3",
      "Reno 3 Pro",
      "Reno 4",
      "Reno 4 Pro",
      "Reno 4F",
      "Reno 4 Lite",
      "Reno 4Z 5G",
      "Reno 5",
      "Reno 5 Pro",
      "Reno 5 Pro+",
      "Reno 5F",
      "Reno 5 Lite",
      "Reno 5Z",
      "Reno 6",
      "Reno 6 Pro",
      "Reno 6 Pro+",
      "Reno 6Z",
      "Reno 6 Lite",
      "Reno 7",
      "Reno 7 Pro",
      "Reno 7Z",
      "Reno 7 Lite",
      "Reno 8",
      "Reno 8 Pro",
      "Reno 8 Pro+",
      "Reno 8T",
      "Reno 8Z",
      "Reno 8 Lite",
      "Reno 9",
      "Reno 9 Pro",
      "Reno 9 Pro+",
      "Reno 10",
      "Reno 10 Pro",
      "Reno 10 Pro+",
      "Reno 11",
      "Reno 11 Pro",
      "Reno 11 F",
      // F series
      "F1",
      "F1 Plus",
      "F1s",
      "F3",
      "F3 Plus",
      "F5",
      "F5 Youth",
      "F7",
      "F9",
      "F9 Pro",
      "F11",
      "F11 Pro",
      "F15",
      "F15 Pro",
      "F17",
      "F17 Pro",
      "F19",
      "F19 Pro",
      "F19 Pro+",
      "F21 Pro",
      "F21 Pro 5G",
      "F23 5G",
      "F25 Pro",
      // A series
      "A1",
      "A1k",
      "A3",
      "A3s",
      "A5",
      "A5s",
      "A7",
      "A7x",
      "A8",
      "A9",
      "A9 2020",
      "A11",
      "A11k",
      "A11s",
      "A12",
      "A15",
      "A15s",
      "A16",
      "A16s",
      "A16e",
      "A16k",
      "A17",
      "A17k",
      "A18",
      "A31",
      "A32",
      "A33",
      "A36",
      "A37",
      "A38",
      "A52",
      "A52s",
      "A53",
      "A54",
      "A55",
      "A57",
      "A57s",
      "A58",
      "A72",
      "A74",
      "A76",
      "A77",
      "A77s",
      "A78",
      "A91",
      "A92",
      "A93",
      "A94",
      "A95",
      "A96",
      "A97",
      "A98",
      // K series
      "K1",
      "K3",
      "K5",
      "K7x",
      "K9",
      "K9 Pro",
      "K10",
      "K10 Pro",
      "K11",
      "K11x",
    ],

    Vivo: [
      // X series
      "X1",
      "X3",
      "X5",
      "X5 Max",
      "X5 Pro",
      "X6",
      "X6 Plus",
      "X7",
      "X7 Plus",
      "X9",
      "X9 Plus",
      "X9s",
      "X9s Plus",
      "X20",
      "X20 Plus",
      "X21",
      "X21s",
      "X21i",
      "X23",
      "X27",
      "X27 Pro",
      "X30",
      "X30 Pro",
      "X50",
      "X50 Pro",
      "X50 Pro+",
      "X50e",
      "X51 5G",
      "X60",
      "X60 Pro",
      "X60 Pro+",
      "X60t",
      "X70",
      "X70 Pro",
      "X70 Pro+",
      "X70t",
      "X80",
      "X80 Pro",
      "X80 Lite",
      "X90",
      "X90 Pro",
      "X90 Pro+",
      "X90s",
      "X100",
      "X100 Pro",
      "X100 Ultra",
      // V series
      "V1",
      "V1s",
      "V3",
      "V3 Max",
      "V5",
      "V5 Plus",
      "V5s",
      "V5 Lite",
      "V7",
      "V7 Plus",
      "V9",
      "V9 Youth",
      "V11",
      "V11 Pro",
      "V11i",
      "V15",
      "V15 Pro",
      "V17",
      "V17 Pro",
      "V19",
      "V19 Neo",
      "V20",
      "V20 Pro",
      "V20 SE",
      "V21",
      "V21 5G",
      "V21e",
      "V21s",
      "V23",
      "V23 Pro",
      "V23e",
      "V25",
      "V25 Pro",
      "V25e",
      "V27",
      "V27 Pro",
      "V27e",
      "V29",
      "V29 Pro",
      "V29e",
      "V30",
      "V30 Pro",
      "V30e",
      // Y series
      "Y01",
      "Y02",
      "Y02s",
      "Y02t",
      "Y03",
      "Y11",
      "Y12",
      "Y12s",
      "Y12a",
      "Y12G",
      "Y15",
      "Y15s",
      "Y15a",
      "Y16",
      "Y17",
      "Y19",
      "Y20",
      "Y20s",
      "Y20G",
      "Y20i",
      "Y21",
      "Y21s",
      "Y21G",
      "Y21T",
      "Y22",
      "Y22s",
      "Y27",
      "Y27s",
      "Y27 5G",
      "Y28",
      "Y30",
      "Y30G",
      "Y31",
      "Y31s",
      "Y33s",
      "Y33T",
      "Y35",
      "Y35m+",
      "Y36",
      "Y50",
      "Y51",
      "Y51a",
      "Y52s",
      "Y53s",
      "Y55",
      "Y55s",
      "Y70",
      "Y72 5G",
      "Y73",
      "Y75",
      "Y75 5G",
      "Y76 5G",
      "Y100",
      "Y100A",
      // S series
      "S1",
      "S1 Pro",
      "S6",
      "S7",
      "S7t",
      "S9",
      "S9e",
      "S10",
      "S10e",
      "S12",
      "S15",
      "S15e",
      "S15 Pro",
      "S16",
      "S16e",
      "S16 Pro",
      "S17",
      "S17e",
      "S17 Pro",
      "S18",
      "S18e",
      "S18 Pro",
      // iQOO series
      "iQOO",
      "iQOO Pro",
      "iQOO 3",
      "iQOO 5",
      "iQOO 5 Pro",
      "iQOO 7",
      "iQOO 7 Legend",
      "iQOO 8",
      "iQOO 8 Pro",
      "iQOO 9",
      "iQOO 9 Pro",
      "iQOO 9 SE",
      "iQOO 10",
      "iQOO 10 Pro",
      "iQOO 11",
      "iQOO 11 Pro",
      "iQOO 11s",
      "iQOO 12",
      "iQOO 12 Pro",
      "iQOO Neo 3",
      "iQOO Neo 5",
      "iQOO Neo 5s",
      "iQOO Neo 5 Lite",
      "iQOO Neo 6",
      "iQOO Neo 6 SE",
      "iQOO Neo 7",
      "iQOO Neo 7 Pro",
      "iQOO Neo 7 SE",
      "iQOO Neo 8",
      "iQOO Neo 8 Pro",
      "iQOO Neo 9",
      "iQOO Neo 9 Pro",
      "iQOO Z1",
      "iQOO Z1x",
      "iQOO Z3",
      "iQOO Z5",
      "iQOO Z5x",
      "iQOO Z6",
      "iQOO Z6 Pro",
      "iQOO Z6 Lite",
      "iQOO Z6x",
      "iQOO Z7",
      "iQOO Z7 Pro",
      "iQOO Z7s",
      "iQOO Z7x",
      "iQOO Z9",
      "iQOO Z9 Turbo",
    ],

    Realme: [
      // GT series
      "Realme GT",
      "Realme GT Master Edition",
      "Realme GT Neo",
      "Realme GT Neo 2",
      "Realme GT Neo 2T",
      "Realme GT Neo 3",
      "Realme GT Neo 3T",
      "Realme GT Neo 5",
      "Realme GT Neo 5 SE",
      "Realme GT 2",
      "Realme GT 2 Pro",
      "Realme GT 3",
      "Realme GT 5",
      "Realme GT 5 Pro",
      "Realme GT 6",
      "Realme GT 6T",
      // Numbered series
      "Realme 1",
      "Realme 2",
      "Realme 2 Pro",
      "Realme 3",
      "Realme 3 Pro",
      "Realme 3i",
      "Realme 5",
      "Realme 5 Pro",
      "Realme 5s",
      "Realme 5i",
      "Realme 6",
      "Realme 6 Pro",
      "Realme 6s",
      "Realme 6i",
      "Realme 7",
      "Realme 7 Pro",
      "Realme 7i",
      "Realme 7 5G",
      "Realme 8",
      "Realme 8 Pro",
      "Realme 8s 5G",
      "Realme 8i",
      "Realme 8 5G",
      "Realme 9",
      "Realme 9 Pro",
      "Realme 9 Pro+",
      "Realme 9i",
      "Realme 9 5G",
      "Realme 9 SE",
      "Realme 10",
      "Realme 10 Pro",
      "Realme 10 Pro+",
      "Realme 10s",
      "Realme 10 5G",
      "Realme 11",
      "Realme 11 Pro",
      "Realme 11 Pro+",
      "Realme 11x 5G",
      "Realme 11 5G",
      "Realme 12",
      "Realme 12 Pro",
      "Realme 12 Pro+",
      "Realme 12x 5G",
      "Realme 12 5G",
      // C series
      "Realme C1",
      "Realme C2",
      "Realme C3",
      "Realme C11",
      "Realme C11 2021",
      "Realme C12",
      "Realme C15",
      "Realme C17",
      "Realme C20",
      "Realme C20A",
      "Realme C21",
      "Realme C21Y",
      "Realme C25",
      "Realme C25s",
      "Realme C25Y",
      "Realme C30",
      "Realme C30s",
      "Realme C31",
      "Realme C33",
      "Realme C35",
      "Realme C51",
      "Realme C53",
      "Realme C55",
      "Realme C67",
      // Narzo series
      "Realme Narzo 10",
      "Realme Narzo 10A",
      "Realme Narzo 20",
      "Realme Narzo 20A",
      "Realme Narzo 20 Pro",
      "Realme Narzo 30",
      "Realme Narzo 30A",
      "Realme Narzo 30 Pro",
      "Realme Narzo 50",
      "Realme Narzo 50A",
      "Realme Narzo 50 Pro",
      "Realme Narzo 50i",
      "Realme Narzo 50i Prime",
      "Realme Narzo 60",
      "Realme Narzo 60 Pro",
      "Realme Narzo 60x",
      // Q series
      "Realme Q",
      "Realme Q2",
      "Realme Q2 Pro",
      "Realme Q2i",
      "Realme Q3",
      "Realme Q3 Pro",
      "Realme Q3i",
      "Realme Q3s",
      "Realme Q3t",
      "Realme Q5",
      "Realme Q5 Pro",
      "Realme Q5i",
    ],

    Infinix: [
      // Zero series
      "Zero",
      "Zero 2",
      "Zero 3",
      "Zero 4",
      "Zero 4 Plus",
      "Zero 5",
      "Zero 5 Pro",
      "Zero 6",
      "Zero 6 Pro",
      "Zero 8",
      "Zero 8i",
      "Zero X",
      "Zero X Pro",
      "Zero X Neo",
      "Zero 20",
      "Zero 30",
      "Zero 30 5G",
      "Zero 40",
      "Zero 40 5G",
      // Note series
      "Note 7",
      "Note 7 Lite",
      "Note 8",
      "Note 8i",
      "Note 10",
      "Note 10 Pro",
      "Note 11",
      "Note 11 Pro",
      "Note 11s",
      "Note 11i",
      "Note 12",
      "Note 12 Pro",
      "Note 12 G96",
      "Note 12 VIP",
      "Note 12i",
      "Note 30",
      "Note 30 Pro",
      "Note 30 VIP",
      "Note 30i",
      "Note 40",
      "Note 40 Pro",
      "Note 40 Pro+",
      "Note 40x",
      // Hot series
      "Hot 6",
      "Hot 6 Pro",
      "Hot 6X",
      "Hot 7",
      "Hot 7 Pro",
      "Hot 8",
      "Hot 8 Lite",
      "Hot 9",
      "Hot 9 Play",
      "Hot 9 Pro",
      "Hot 10",
      "Hot 10 Lite",
      "Hot 10 Play",
      "Hot 10 Pro",
      "Hot 10s",
      "Hot 10i",
      "Hot 11",
      "Hot 11 Play",
      "Hot 11 2022",
      "Hot 11s",
      "Hot 11s NFC",
      "Hot 12",
      "Hot 12 Play",
      "Hot 12 Pro",
      "Hot 12i",
      "Hot 20",
      "Hot 20 Play",
      "Hot 20 Pro",
      "Hot 20s",
      "Hot 20i",
      "Hot 30",
      "Hot 30 Play",
      "Hot 30 Pro",
      "Hot 30i",
      "Hot 40",
      "Hot 40 Pro",
      "Hot 40i",
      // Smart series
      "Smart 5",
      "Smart 6",
      "Smart 6 Plus",
      "Smart 6 HD",
      "Smart 7",
      "Smart 7 HD",
      "Smart 8",
      "Smart 8 HD",
      "Smart 8 Plus",
      // GT series
      "GT 10",
      "GT 10 Pro",
      "GT 20 Pro",
    ],

    Tecno: [
      // Phantom series
      "Phantom 6",
      "Phantom 6 Plus",
      "Phantom 8",
      "Phantom 8 Plus",
      "Phantom 9",
      "Phantom X",
      "Phantom X2",
      "Phantom X2 Pro",
      "Phantom V Fold",
      "Phantom V Flip",
      // Camon series
      "Camon 11",
      "Camon 11 Pro",
      "Camon 12",
      "Camon 12 Pro",
      "Camon 12 Air",
      "Camon 15",
      "Camon 15 Pro",
      "Camon 15 Air",
      "Camon 16",
      "Camon 16 Pro",
      "Camon 16 Premier",
      "Camon 16S",
      "Camon 17",
      "Camon 17 Pro",
      "Camon 17P",
      "Camon 18",
      "Camon 18 Pro",
      "Camon 18 Premier",
      "Camon 18P",
      "Camon 19",
      "Camon 19 Pro",
      "Camon 19 Neo",
      "Camon 20",
      "Camon 20 Pro",
      "Camon 20 Premier",
      "Camon 20 Pro 5G",
      "Camon 30",
      "Camon 30 Pro",
      "Camon 30 Premier",
      // Spark series
      "Spark 1",
      "Spark 2",
      "Spark 3",
      "Spark 3 Pro",
      "Spark 4",
      "Spark 4 Lite",
      "Spark 4 Air",
      "Spark 5",
      "Spark 5 Pro",
      "Spark 5 Air",
      "Spark 6",
      "Spark 6 Go",
      "Spark 6 Air",
      "Spark 7",
      "Spark 7 Pro",
      "Spark 7T",
      "Spark 7P",
      "Spark 8",
      "Spark 8 Pro",
      "Spark 8C",
      "Spark 8P",
      "Spark 9",
      "Spark 9 Pro",
      "Spark 9T",
      "Spark 9 Play",
      "Spark 10",
      "Spark 10 Pro",
      "Spark 10C",
      "Spark 10 NFC",
      "Spark 20",
      "Spark 20 Pro",
      "Spark 20 Pro+",
      "Spark 20C",
      // Pop series
      "Pop 2F",
      "Pop 3",
      "Pop 4",
      "Pop 4 Pro",
      "Pop 4 LTE",
      "Pop 5",
      "Pop 5 Pro",
      "Pop 5 LTE",
      "Pop 5 Go",
      "Pop 6",
      "Pop 6 Pro",
      "Pop 6 Go",
      "Pop 7",
      "Pop 7 Pro",
      "Pop 8",
      // Pova series
      "Pova",
      "Pova 2",
      "Pova 3",
      "Pova 4",
      "Pova 4 Pro",
      "Pova 5",
      "Pova 5 Pro",
      "Pova 6",
      "Pova 6 Pro",
      "Pova Neo",
      "Pova Neo 2",
      "Pova Neo 3",
    ],

    ASUS: [
      // ROG Phone series
      "ROG Phone",
      "ROG Phone II",
      "ROG Phone 3",
      "ROG Phone 3 Strix",
      "ROG Phone 5",
      "ROG Phone 5s",
      "ROG Phone 5s Pro",
      "ROG Phone 5 Pro",
      "ROG Phone 5 Ultimate",
      "ROG Phone 6",
      "ROG Phone 6 Pro",
      "ROG Phone 6D",
      "ROG Phone 6D Ultimate",
      "ROG Phone 7",
      "ROG Phone 7 Pro",
      "ROG Phone 7 Ultimate",
      "ROG Phone 8",
      "ROG Phone 8 Pro",
      // Zenfone series
      "Zenfone 3",
      "Zenfone 3 Deluxe",
      "Zenfone 3 Laser",
      "Zenfone 3 Max",
      "Zenfone 3 Zoom",
      "Zenfone 4",
      "Zenfone 4 Max",
      "Zenfone 4 Pro",
      "Zenfone 4 Selfie",
      "Zenfone 4 Selfie Pro",
      "Zenfone 5",
      "Zenfone 5Z",
      "Zenfone 5 Lite",
      "Zenfone 6",
      "Zenfone 7",
      "Zenfone 7 Pro",
      "Zenfone 8",
      "Zenfone 8 Flip",
      "Zenfone 8 Mini",
      "Zenfone 9",
      "Zenfone 10",
      "Zenfone 11 Ultra",
    ],

    Google: [
      // Pixel series
      "Pixel",
      "Pixel XL",
      "Pixel 2",
      "Pixel 2 XL",
      "Pixel 3",
      "Pixel 3 XL",
      "Pixel 3a",
      "Pixel 3a XL",
      "Pixel 4",
      "Pixel 4 XL",
      "Pixel 4a",
      "Pixel 4a 5G",
      "Pixel 5",
      "Pixel 5a",
      "Pixel 6",
      "Pixel 6 Pro",
      "Pixel 6a",
      "Pixel 7",
      "Pixel 7 Pro",
      "Pixel 7a",
      "Pixel 7 Fold",
      "Pixel 8",
      "Pixel 8 Pro",
      "Pixel 8a",
      "Pixel 8 Fold",
      "Pixel Fold",
    ],

    Nothing: [
      "Phone (1)",
      "Phone (2)",
      "Phone (2a)",
      "Phone (2a) Plus",
    ],

    OnePlus: [
      // Numbered series
      "OnePlus One",
      "OnePlus 2",
      "OnePlus 3",
      "OnePlus 3T",
      "OnePlus 5",
      "OnePlus 5T",
      "OnePlus 6",
      "OnePlus 6T",
      "OnePlus 7",
      "OnePlus 7 Pro",
      "OnePlus 7T",
      "OnePlus 7T Pro",
      "OnePlus 8",
      "OnePlus 8 Pro",
      "OnePlus 8T",
      "OnePlus 9",
      "OnePlus 9 Pro",
      "OnePlus 9R",
      "OnePlus 9RT",
      "OnePlus 10 Pro",
      "OnePlus 10R",
      "OnePlus 10T",
      "OnePlus 11",
      "OnePlus 11R",
      "OnePlus 12",
      "OnePlus 12R",
      "OnePlus Open",
      // Nord series
      "OnePlus Nord",
      "OnePlus Nord 2",
      "OnePlus Nord 2T",
      "OnePlus Nord 3",
      "OnePlus Nord 4",
      // Nord CE series
      "OnePlus Nord CE",
      "OnePlus Nord CE 2",
      "OnePlus Nord CE 2 Lite",
      "OnePlus Nord CE 3",
      "OnePlus Nord CE 3 Lite",
      "OnePlus Nord CE 4",
      "OnePlus Nord CE 4 Lite",
      // Nord N series
      "OnePlus Nord N10 5G",
      "OnePlus Nord N100",
      "OnePlus Nord N20 5G",
      "OnePlus Nord N200 5G",
      "OnePlus Nord N20 SE",
      "OnePlus Nord N30 5G",
      "OnePlus Nord N300 5G",
      "OnePlus Nord N30 SE",
    ],

    Motorola: [
      // Moto G series
      "Moto G4",
      "Moto G4 Play",
      "Moto G4 Plus",
      "Moto G5",
      "Moto G5 Plus",
      "Moto G5s",
      "Moto G5s Plus",
      "Moto G6",
      "Moto G6 Play",
      "Moto G6 Plus",
      "Moto G7",
      "Moto G7 Play",
      "Moto G7 Plus",
      "Moto G7 Power",
      "Moto G8",
      "Moto G8 Play",
      "Moto G8 Plus",
      "Moto G8 Power",
      "Moto G8 Power Lite",
      "Moto G9",
      "Moto G9 Play",
      "Moto G9 Plus",
      "Moto G9 Power",
      "Moto G10",
      "Moto G10 Power",
      "Moto G20",
      "Moto G30",
      "Moto G31",
      "Moto G40 Fusion",
      "Moto G41",
      "Moto G42",
      "Moto G50",
      "Moto G50 5G",
      "Moto G51 5G",
      "Moto G52",
      "Moto G53 5G",
      "Moto G54 5G",
      "Moto G60",
      "Moto G60s",
      "Moto G62 5G",
      "Moto G71 5G",
      "Moto G72",
      "Moto G73 5G",
      "Moto G82 5G",
      "Moto G84 5G",
      "Moto G100",
      "Moto G200 5G",
      // Moto E series
      "Moto E4",
      "Moto E4 Plus",
      "Moto E5",
      "Moto E5 Play",
      "Moto E5 Plus",
      "Moto E6",
      "Moto E6 Play",
      "Moto E6 Plus",
      "Moto E6s",
      "Moto E6i",
      "Moto E7",
      "Moto E7 Plus",
      "Moto E7 Power",
      "Moto E7i Power",
      "Moto E20",
      "Moto E22",
      "Moto E22i",
      "Moto E22s",
      "Moto E32",
      "Moto E32s",
      "Moto E40",
      // Edge series
      "Motorola Edge",
      "Motorola Edge+",
      "Motorola Edge 20",
      "Motorola Edge 20 Lite",
      "Motorola Edge 20 Pro",
      "Motorola Edge 20 Fusion",
      "Motorola Edge 30",
      "Motorola Edge 30 Lite",
      "Motorola Edge 30 Neo",
      "Motorola Edge 30 Pro",
      "Motorola Edge 30 Fusion",
      "Motorola Edge 30 Ultra",
      "Motorola Edge 40",
      "Motorola Edge 40 Neo",
      "Motorola Edge 40 Pro",
      "Motorola Edge 50",
      "Motorola Edge 50 Fusion",
      "Motorola Edge 50 Neo",
      "Motorola Edge 50 Pro",
      "Motorola Edge 50 Ultra",
      // Razr series
      "Motorola Razr 2019",
      "Motorola Razr 5G",
      "Motorola Razr 2022",
      "Motorola Razr 40",
      "Motorola Razr 40 Ultra",
      "Motorola Razr+",
    ],

    Sony: [
      // Xperia 1 series
      "Xperia 1",
      "Xperia 1 II",
      "Xperia 1 III",
      "Xperia 1 IV",
      "Xperia 1 V",
      "Xperia 1 VI",
      // Xperia 5 series
      "Xperia 5",
      "Xperia 5 II",
      "Xperia 5 III",
      "Xperia 5 IV",
      "Xperia 5 V",
      // Xperia 10 series
      "Xperia 10",
      "Xperia 10 Plus",
      "Xperia 10 II",
      "Xperia 10 III",
      "Xperia 10 III Lite",
      "Xperia 10 IV",
      "Xperia 10 V",
      "Xperia 10 VI",
      // Xperia Pro series
      "Xperia Pro",
      "Xperia Pro-I",
      // Other Xperia
      "Xperia L4",
      "Xperia L3",
      "Xperia L2",
      "Xperia XZ3",
      "Xperia XZ2",
      "Xperia XZ2 Compact",
      "Xperia XZ2 Premium",
      "Xperia XZ1",
      "Xperia XZ1 Compact",
      "Xperia XZ Premium",
      "Xperia XZ",
      "Xperia X Compact",
      "Xperia X Performance",
    ],

    Honor: [
      // Magic series
      "Honor Magic",
      "Honor Magic 2",
      "Honor Magic 3",
      "Honor Magic 3 Pro",
      "Honor Magic 3 Pro+",
      "Honor Magic 4",
      "Honor Magic 4 Pro",
      "Honor Magic 4 Ultimate",
      "Honor Magic 5",
      "Honor Magic 5 Pro",
      "Honor Magic 5 Ultimate",
      "Honor Magic 5 Lite",
      "Honor Magic 6",
      "Honor Magic 6 Pro",
      "Honor Magic 6 Ultimate",
      "Honor Magic 6 Lite",
      "Honor Magic V",
      "Honor Magic V2",
      "Honor Magic Vs",
      // Numbered series
      "Honor 50",
      "Honor 50 Lite",
      "Honor 50 Pro",
      "Honor 60",
      "Honor 60 Pro",
      "Honor 60 SE",
      "Honor 70",
      "Honor 70 Lite",
      "Honor 70 Pro",
      "Honor 70 Pro+",
      "Honor 80",
      "Honor 80 GT",
      "Honor 80 Pro",
      "Honor 80 SE",
      "Honor 90",
      "Honor 90 GT",
      "Honor 90 Lite",
      "Honor 90 Pro",
      "Honor 90 Smart",
      "Honor 100",
      "Honor 100 Pro",
      // X series
      "Honor X6",
      "Honor X6a",
      "Honor X6b",
      "Honor X7",
      "Honor X7a",
      "Honor X7b",
      "Honor X8",
      "Honor X8a",
      "Honor X8b",
      "Honor X9",
      "Honor X9a",
      "Honor X9b",
      "Honor X9 5G",
      // Play series
      "Honor Play 5",
      "Honor Play 5T",
      "Honor Play 6C",
      "Honor Play 6T",
      "Honor Play 7",
      "Honor Play 7T",
      "Honor Play 8T",
      "Honor Play 40 Plus",
      "Honor Play 40C",
    ],

    Nokia: [
      // G series
      "Nokia G10",
      "Nokia G11",
      "Nokia G11 Plus",
      "Nokia G20",
      "Nokia G21",
      "Nokia G22",
      "Nokia G42 5G",
      "Nokia G50",
      "Nokia G60 5G",
      // C series
      "Nokia C01 Plus",
      "Nokia C02",
      "Nokia C10",
      "Nokia C12",
      "Nokia C20",
      "Nokia C20 Plus",
      "Nokia C21",
      "Nokia C21 Plus",
      "Nokia C22",
      "Nokia C30",
      "Nokia C31",
      "Nokia C32",
      // X series
      "Nokia X10",
      "Nokia X20",
      "Nokia X30 5G",
      "Nokia XR20",
      // Numbered series
      "Nokia 1",
      "Nokia 1 Plus",
      "Nokia 2",
      "Nokia 2.1",
      "Nokia 2.2",
      "Nokia 2.3",
      "Nokia 2.4",
      "Nokia 3",
      "Nokia 3.1",
      "Nokia 3.1 Plus",
      "Nokia 3.2",
      "Nokia 3.4",
      "Nokia 4.2",
      "Nokia 5",
      "Nokia 5.1",
      "Nokia 5.1 Plus",
      "Nokia 5.3",
      "Nokia 5.4",
      "Nokia 6",
      "Nokia 6.1",
      "Nokia 6.1 Plus",
      "Nokia 6.2",
      "Nokia 7",
      "Nokia 7 Plus",
      "Nokia 7.1",
      "Nokia 7.2",
      "Nokia 7.3 5G",
      "Nokia 8",
      "Nokia 8.1",
      "Nokia 8.3 5G",
      "Nokia 9 PureView",
    ],

    Huawei: [
      // P series
      "P8",
      "P8 Lite",
      "P9",
      "P9 Lite",
      "P9 Plus",
      "P10",
      "P10 Lite",
      "P10 Plus",
      "P20",
      "P20 Lite",
      "P20 Pro",
      "P30",
      "P30 Lite",
      "P30 Pro",
      "P40",
      "P40 Lite",
      "P40 Lite E",
      "P40 Pro",
      "P40 Pro+",
      "P50",
      "P50 Pro",
      "P50 Pocket",
      "P60",
      "P60 Pro",
      "P60 Art",
      // Mate series
      "Mate 7",
      "Mate 8",
      "Mate 9",
      "Mate 9 Pro",
      "Mate 10",
      "Mate 10 Lite",
      "Mate 10 Pro",
      "Mate 20",
      "Mate 20 Lite",
      "Mate 20 Pro",
      "Mate 20 X",
      "Mate 30",
      "Mate 30 Lite",
      "Mate 30 Pro",
      "Mate 40",
      "Mate 40 Pro",
      "Mate 40 Pro+",
      "Mate 50",
      "Mate 50 Pro",
      "Mate 50 RS",
      "Mate 60",
      "Mate 60 Pro",
      "Mate 60 Pro+",
      "Mate 60 RS",
      "Mate X",
      "Mate X2",
      "Mate Xs",
      "Mate Xs 2",
      // Nova series
      "Nova",
      "Nova 2",
      "Nova 2 Plus",
      "Nova 2i",
      "Nova 2s",
      "Nova 3",
      "Nova 3i",
      "Nova 3e",
      "Nova 4",
      "Nova 4e",
      "Nova 5",
      "Nova 5 Pro",
      "Nova 5i",
      "Nova 5T",
      "Nova 5z",
      "Nova 6",
      "Nova 6 SE",
      "Nova 6 5G",
      "Nova 7",
      "Nova 7 SE",
      "Nova 7 Pro",
      "Nova 7i",
      "Nova 8",
      "Nova 8 SE",
      "Nova 8 Pro",
      "Nova 8i",
      "Nova 9",
      "Nova 9 SE",
      "Nova 9 Pro",
      "Nova 10",
      "Nova 10 SE",
      "Nova 10 Pro",
      "Nova 11",
      "Nova 11 SE",
      "Nova 11 Pro",
      "Nova 11 Ultra",
      "Nova 12",
      "Nova 12 SE",
      "Nova 12 Pro",
      "Nova 12 Ultra",
      // Y series
      "Y5",
      "Y5 2019",
      "Y5p",
      "Y6",
      "Y6 2019",
      "Y6p",
      "Y6s",
      "Y7",
      "Y7 2019",
      "Y7p",
      "Y7a",
      "Y8p",
      "Y8s",
      "Y9",
      "Y9 2019",
      "Y9 Prime 2019",
      "Y9a",
      "Y9s",
    ],

    Meizu: [
      "Meizu 15",
      "Meizu 15 Plus",
      "Meizu 15 Lite",
      "Meizu 16",
      "Meizu 16 Plus",
      "Meizu 16X",
      "Meizu 16s",
      "Meizu 16s Pro",
      "Meizu 16T",
      "Meizu 16Xs",
      "Meizu 17",
      "Meizu 17 Pro",
      "Meizu 18",
      "Meizu 18 Pro",
      "Meizu 18s",
      "Meizu 18s Pro",
      "Meizu 18X",
      "Meizu 19",
      "Meizu 19 Pro",
      "Meizu 20",
      "Meizu 20 Pro",
      "Meizu 20 Infinity",
      "Meizu 21",
      "Meizu 21 Pro",
      "Meizu 21 Note",
    ],

    ZTE: [
      // Axon series
      "Axon 30",
      "Axon 30 Pro",
      "Axon 30 Ultra",
      "Axon 30 5G",
      "Axon 40",
      "Axon 40 Pro",
      "Axon 40 Ultra",
      "Axon 50",
      "Axon 50 Ultra",
      // Blade series
      "Blade A31",
      "Blade A31 Plus",
      "Blade A51",
      "Blade A52",
      "Blade A53",
      "Blade A53 Pro",
      "Blade A54",
      "Blade A71",
      "Blade A72",
      "Blade A72 5G",
      "Blade V30",
      "Blade V30 Vita",
      "Blade V40",
      "Blade V40 Design",
      "Blade V40 Pro",
      "Blade V40s",
      "Blade V50 Design",
      // nubia Z series
      "nubia Z30 Pro",
      "nubia Z40 Pro",
      "nubia Z40S Pro",
      "nubia Z50",
      "nubia Z50 Pro",
      "nubia Z50 Ultra",
      "nubia Z50S Pro",
      // nubia Red Magic series
      "nubia Red Magic 3",
      "nubia Red Magic 3S",
      "nubia Red Magic 5G",
      "nubia Red Magic 5S",
      "nubia Red Magic 6",
      "nubia Red Magic 6 Pro",
      "nubia Red Magic 6R",
      "nubia Red Magic 6S Pro",
      "nubia Red Magic 7",
      "nubia Red Magic 7 Pro",
      "nubia Red Magic 7S",
      "nubia Red Magic 7S Pro",
      "nubia Red Magic 8 Pro",
      "nubia Red Magic 8 Pro+",
      "nubia Red Magic 8S Pro",
      "nubia Red Magic 8S Pro+",
      "nubia Red Magic 9 Pro",
      "nubia Red Magic 9 Pro+",
      "nubia Red Magic 9S Pro",
    ],

    Lenovo: [
      // Legion Phone series
      "Legion Phone Duel",
      "Legion Phone Duel 2",
      "Legion Phone Duel 3",
      "Legion Phone 3 Pro",
      // K series
      "K5 Note",
      "K5 Pro",
      "K6",
      "K6 Note",
      "K6 Power",
      "K8",
      "K8 Note",
      "K8 Plus",
      "K9",
      "K9 Note",
      "K10",
      "K10 Note",
      "K10 Plus",
      "K12",
      "K12 Note",
      "K12 Pro",
      "K13",
      "K13 Note",
      "K13 Pro",
      "K14",
      "K14 Plus",
      // Z series
      "Z5",
      "Z5 Pro",
      "Z5 Pro GT",
      "Z5s",
      "Z6",
      "Z6 Lite",
      "Z6 Pro",
      "Z6 Youth",
    ],

    BlackBerry: [
      "BlackBerry Priv",
      "BlackBerry DTEK50",
      "BlackBerry DTEK60",
      "BlackBerry KEYone",
      "BlackBerry Motion",
      "BlackBerry KEY2",
      "BlackBerry KEY2 LE",
      "BlackBerry Evolve",
      "BlackBerry Evolve X",
    ],
  },
};

// Helper functions
export function getBrands(os: OsKey): string[] {
  return Object.keys(DEVICE_DATA[os]);
}

export function getModels(os: OsKey, brand: string): string[] {
  return DEVICE_DATA[os][brand] ?? [];
}

// Options arrays
export const RAM_OPTIONS: string[] = [
  "2GB",
  "3GB",
  "4GB",
  "6GB",
  "8GB",
  "12GB",
  "16GB",
  "24GB",
];

export const STORAGE_OPTIONS: string[] = [
  "32GB",
  "64GB",
  "128GB",
  "256GB",
  "512GB",
  "1TB",
];

export const OS_OPTIONS: OsKey[] = ["iOS", "Android"];
